### ISSUE TITLE
Is it possible to check programmatically if any external HTTP requests were made after a run?

### ISSUE THREAD

**Issue by Ross65536** [trusche/httplog#101]
It would be useful to be able to tell if any HTTP requests were made after an execution (for example to check if any tests are not using stubs for HTTP)

**Comment by trusche** [comment]
Interesting use case. However, that's not really the purpose of this gem. 

I guess what you can do is check the logfile output for the absence of any line containing `httplog`. For stubbed HTTP calls, those should not be present.

Or you could assert that `HttpLog.call` is not called, something like `expect(HttpLog).to_not receive(:call)` (rspec). That should error if any library that HttpLog supports does in fact make a request.
