### ISSUE TITLE
Version 1.6 Changelog Documentation

### ISSUE THREAD

**Issue by kevin-j-m** [trusche/httplog#125]
Congrats on the 1.6.0 release! Will there be a [changelog](https://github.com/trusche/httplog/blob/master/CHANGELOG.md) entry added to highlight what's included? Thanks.

**Comment by olleolleolle** [comment]
https://github.com/trusche/httplog/commit/4eb58ac525847252efbae29a885245a87465cacb Seems like this commit added it! Hope this helps!

**Comment by kevin-j-m** [comment]
Thank you!
