### ISSUE TITLE
config.severity doesn't change log level

### ISSUE THREAD

**Issue by dushanstoryful** [trusche/httplog#139]
Changing the `config.severity = Logger::Severity::DEBUG` to `config.severity = Logger::Severity::ERROR` only changes the keyword in the logs without affecting the actual log output in Ruby on Rails. 

**Example:/-**
`[2024-02-28T14:46:34.027248 #1] DEBUG -- : [httplog] {"method":"POST","url":"http..........`
`[2024-02-28T14:46:34.027248 #1] ERROR -- : [httplog] {"method":"POST","url":"http..........`

**Comment by panozzaj** [comment]
(Not a maintainer, just a user of this library)

When I change the `severity` in our application using the latest version of the gem (1.6.3), it does seem to change the level. For example, if my Rails log level is `INFO` and I set the `severity` to `Logger::Severity::DEBUG`, then I don't see any `[httplog]`s, but if I change the severity to `INFO` or higher, then I see the errors. Maybe double-check your Rails log level in the environment you're logging in? Hope this helps!

**Comment by trusche** [comment]
@dushanstoryful sorry for the slow response. I can't reproduce this, so if it's still an issue, could you provide a bit more context? Is this with Rails? Any non-standard logger?
