### ISSUE TITLE
httparty benchmarking is inaccurate

### ISSUE THREAD

**Issue by russellsilva** [trusche/httplog#17]
D, [2014-08-26T13:08:48.821528 #6500] DEBUG -- : [httplog] Connecting: example.com:443
    D, [2014-08-26T13:08:49.292332 #6500] DEBUG -- : [httplog] Sending: GET https://example.com
    D, [2014-08-26T13:08:49.335191 #6500] DEBUG -- : [httplog] Status: 200
    D, [2014-08-26T13:08:49.335292 #6500] DEBUG -- : [httplog] Benchmark: 0.042724323 seconds

As can be seen in the above log excerpt (URL changed) the benchmarking does not include the connection time between the first and second lines. Is that intentional? Using httparty.

**Comment by trusche** [comment]
Hi @russellsilva - sorry, somehow I missed the notification for this issue. Better late then never. I'll look into it, it's not intentional.

**Comment by trusche** [comment]
The benchmarking covers the HTTP request once the connection is open. Not ideal, but much easier to implement because it's confined to a single method in all adapters. So I think I'll leave it as is for now. I'll add a note to the README.
