### ISSUE TITLE
Why httplog gem is not recommended to use for production environment?

### ISSUE THREAD

**Issue by Srinivas5028** [trusche/httplog#18]
Why httplog gem is not recommended to use for production environment, can you please explain about this briefly?

**Comment by andrhamm** [comment]
It is extremely verbose and logs will fill up your filesystem if not managed correctly. It also potentially logs sensitive data that is best not left sitting around. That being said, If you understand the tool, using it in production is fine. I do.

**Comment by trusche** [comment]
My main reason for warning against its use in production is that it hooks into the networking code on a fairly low level in some cases. It may have side effects or performance issues that would be pretty hard to troubleshoot in production.
