### ISSUE TITLE
Support for HTTP

### ISSUE THREAD

**Issue by christhekeele** [trusche/httplog#19]
Any thoughts about supporting the [http](https://github.com/httprb/http.rb) library? I don't believe it has any default logger support.

**Comment by trusche** [comment]
@christhekeele I'll take a look, unless you'd like to take a stab at it yourself?

**Comment by christhekeele** [comment]
Yeah, I'll hack on a PR tonight. The `httplog` interface looks simple enough to use, and the guts of `http` are pretty straight-forward too.

**Comment by christhekeele** [comment]
Took an initial stab at it [here](https://github.com/christhekeele/httplog/tree/add-http-support). It's pretty straight forward, but one of the tests is failing: `http` auto-capitalizes headers and the headers spec is case-sensitive.

**Comment by christhekeele** [comment]
Seems a lot of the other adapters downcase the header keys, so simply modifying the expectations to work on titleized headers fails 4 other tests.

I've treated it as in implementation detail and downcased both in the tests.

**Comment by trusche** [comment]
Thanks! Merged and released as 0.2.8.

**Comment by christhekeele** [comment]
:tada: :smile_cat:
