### ISSUE TITLE
log writing failed. "\xC2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by Qwertyn** [trusche/httplog#28]
Hello!

Sometimes there is an error type:
```
log writing failed. "\xC2" from ASCII-8BIT to UTF-8
```
"\xC2"  - example. There are other characters

It was possible to find out what it is in response.

Can I use the following approach or is it something fraught?
msg.force_encoding('UTF-8')

```ruby
# httplog/lib/httplog/http_log.rb 
module HttpLog
  ...
  class << self
    ...
    def log(msg)
      severities = Hash[*Logger::Severity.constants.enum_for(:each_with_index).collect{ |s, i| [i, s] }.flatten]
      severity = severities[options[:severity]].to_s.downcase
      options[:logger].send(severity, colorize(LOG_PREFIX + msg.force_encoding('UTF-8')))
    end
    ...
  end
  ...
end
```

**Comment by trusche** [comment]
Hi @Qwertyn, would you mind giving the master branch a try? I believe I've finally fixed this issue, at least for POST data, but it's possible it would crop up somewhere else - please let me know if you still encounter it with this version.

**Comment by trusche** [comment]
I've published v0.2.15 which should fix this at the cost of no longer unescaping URI-encoded data.

**Comment by Qwertyn** [comment]
I tried master branch.
Error is reproduced.
The thing is that these characters are found in a response.
Response is handled by log_body:

```ruby
# httplog/lib/httplog/http_log.rb 
module HttpLog
  ...
  class << self
    ...
    def log_body(body, encoding = nil)
      ...
        else
          log("Response:\n#{body.to_s.force_encoding("UTF-8")}")  # <<<<  It helped me
        end
      end
    end
  end
end
```

Even better, in my opinion, do it all in one place
```ruby
def log(msg)
  # here
```

**Comment by Qwertyn** [comment]
@trusche, Say what?

**Comment by trusche** [comment]
Yep, I'm combining yours with his, hopefully that'll do it. Thanks for your patience.

**Comment by Qwertyn** [comment]
:+1: Thanks!
We are waiting for version update :-)

**Comment by cavneb** [comment]
:+1:

**Comment by trusche** [comment]
@cavneb just to be sure - are you saying you're still encountering this issue? Or that you like the fix? :)
