### ISSUE TITLE
issue with httpclient 2.7.1

### ISSUE THREAD

**Issue by pic** [trusche/httplog#31]
signature of #create_socket has changed in httpclient between 2.6.0.1

```httpclient/session.rb:    def create_socket(site)```

and 2.7.1

```httpclient/session.rb:    def create_socket(host, port)```

httplog is not compatible with the most up to date signature.

**Comment by trusche** [comment]
Thanks for reporting this - fixed, will release new version shortly.

**Comment by trusche** [comment]
v0.3.2 is available from rubygems.org.

**Comment by pic** [comment]
great, works like a charm, thanks
