### ISSUE TITLE
Is it possible to save logs in a specific file?

### ISSUE THREAD

**Issue by bakeris** [trusche/httplog#47]
Hello All,
I have installed httplog through gemfile. Everything is working fine but i want to get all the logs in a file rather than outputted directly in the terminal.
Could someone give me a help?
Regards

**Comment by trusche** [comment]
Hi @bakeris - can you give me a bit more context? Are you using this in pure ruby, or within a Rails application? Can you just redirect all of stdout to a file, or is there additional output that you don't want to redirect?

**Comment by bakeris** [comment]
@trusche sorry I am using it with rails and just want to save things in a file.

**Comment by trusche** [comment]
All you need to do is specify your own logger in the configuration. For example:

````
  HttpLog.configure do |config|
    config.logger = Logger.new('log/example.log')
  end
```

Hope that helps.

**Comment by bakeris** [comment]
Thanks
