### ISSUE TITLE
Rack 2.0 dependency

### ISSUE THREAD

**Issue by tycooon** [trusche/httplog#57]
Hi, why is rack required for this gem? It can be used without web app at all, right? I have problems with some legacy app:

```
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    httplog (= 1.0.1) was resolved to 1.0.1, which depends on
      rack (~> 2.0)

    sprockets (~> 2.11.0) was resolved to 2.11.3, which depends on
      rack (~> 1.0)
```

**Comment by trusche** [comment]
It's using Rack to decode HTTP status codes - see https://github.com/trusche/httplog/pull/46. Admittedly it could be done without. I'll see if I can make it less strict, it should work with Rack v1. Stay tuned.

**Comment by trusche** [comment]
I've loosened the dependency to `rack >= 1.0`. Could you give it a try from master, and if that solves your issue, I'll release it as a version bump?

**Comment by tycooon** [comment]
It works, a new release would be cool!

**Comment by tycooon** [comment]
By the way, it looks like some of gemfiles are missing in repo (http3 and rake2) and it's strange to me that travis is not complaining about that.

**Comment by trusche** [comment]
They were still cached on Travis I assume. I added them back (was hoping I don' need to version that's in `Gemfile.lock`, but no dice). 

v1.0.2 released.
