### ISSUE TITLE
colorize runtime dependency is GPL 2.0

### ISSUE THREAD

**Issue by cgriego** [trusche/httplog#59]
httplog is licensed as MIT, but the colorize runtime dependency is licensed as GPL 2.0. Would you consider changes to httplog that remove the dependency or replacing it with an alternative (like [rainbow](https://rubygems.org/gems/rainbow)) so that code that can't comply with GPL can use httplog?

**Comment by trusche** [comment]
Absolutely, I haven't paid attention to that. Stay tuned.

**Comment by trusche** [comment]
Released version 1.1.0. Thanks again for pointing that out.

**Comment by cgriego** [comment]
Thanks @trusche!
