### ISSUE TITLE
are aws-sdk / amazon request logs also visible through httplog

### ISSUE THREAD

**Issue by umarsheikh** [trusche/httplog#64]
I have a project with aws-sdk gem. Are their logs also visible through httplog? What does aws-sdk gem use to make http requests?

**Comment by trusche** [comment]
Yes, requests made by asw-sdk should be logged, it uses net/http under the hood. Have you tried it?

**Comment by umarsheikh** [comment]
yes, i tried it and there was nothing logged. But just today, I require'd 'httplog' and then i could see the requests made in the logs, which proved very helpful. Thanks!
