### ISSUE TITLE
Bug: Ethon adapter fails when response headers are empty

### ISSUE THREAD

**Issue by RKushnir** [trusche/httplog#67]
When using the Ethon adapter and when the `response_headers` is an empty string, this code produces `nil`
https://github.com/trusche/httplog/blob/730c30175b7bc7e6ec7bc75b96526bfee33bb680/lib/httplog/adapters/ethon.rb#L29-L31

which then causes a crash when calling `map` on it:
https://github.com/trusche/httplog/blob/730c30175b7bc7e6ec7bc75b96526bfee33bb680/lib/httplog/adapters/ethon.rb#L40

**Comment by trusche** [comment]
Hmm. Hard to write a test for, since it takes some doing to send a HTTP response without any headers :) Anyway, this should fix it, can you give it a whirl from master?

**Comment by RKushnir** [comment]
😄

**Comment by RKushnir** [comment]
@trusche Works good, thank you. Could you make a new release?
