### ISSUE TITLE
question: is blacklisting supposed to prevent the request from being sent?

### ISSUE THREAD

**Issue by neojin** [trusche/httplog#69]
Upon initial reading it seems like blacklisting is a way to tell httplog not to log a http request if the URL matches the blacklist. I gave this a try with httprb, and when I blacklist a URL, it seems like it doesn't send the request at all.

Which leads me to the question - is the blacklist only supposed to prevent logging of the request, or to prevent the request itself being sent?

https://github.com/trusche/httplog/blob/9a853a96f3db8656d9ed90c817d19d3fe9009d02/lib/httplog/adapters/http.rb#L11-L40

When I read the source here above, there is no corresponding `else` for `if HttpLog.url_approved?(req.uri)`, so it seems like the request is not sent at all. Is this the correct behavior?

**Comment by trusche** [comment]
It's definitely not supposed to prevent the request. That's a bug. I'll fix it unless you feel like submitting a PR :)

**Comment by neojin** [comment]
Thanks for confirming! Will try to have a PR out tomorrow
